# Refer to https://kubernetes.io/docs/setup/independent/install-kubeadm/
#
- name: Disable swap [1/2]
  shell: swapoff -a

- name: Disable swap [2/2]
  shell: sed -i '/ swap / d' /etc/fstab

- name: Stop SELinux Enforcing [1/2]
  shell: setenforce 0

- name: Stop SELinux Enforcing [2/2]
  shell: sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

- name: Disable firewalld service
  service: name=firewalld state=stopped enabled=no

- name: Yum install yum-utils device-mapper-persistent-data lvm2
  yum: 
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state:
      present
      
- name: Add repository
  copy: src=docker-ce.repo dest=/etc/yum.repos.d/docker-ce.repo

- name: Yum install docker
  yum: name=docker-ce-18.06.0.ce state=present

- name: Enable and start Docker service
  service: name=docker state=started enabled=yes

- name: Transfer kubernetes.repo
  copy: src=kubernetes.repo dest=/etc/yum.repos.d/kubernetes.repo

- name: Transfer file k8s.conf
  copy: src=k8s.conf dest=/etc/sysctl.d/k8s.conf

- name: Set system parameters for k8s
  shell: sysctl --system

- name: Yum install kubelet kubeadm kubectl
  yum: 
    name:
      - kubelet-{{ K8S_VERSION }}
      - kubeadm-{{ K8S_VERSION }}
      - kubectl-{{ K8S_VERSION }}
    state:
      present
    disable_gpg_check:
      yes

- name: Enable and start kubelet service
  service: name=kubelet state=started enabled=yes

- name: Yum install epel-release
  yum:
    name:
      - epel-release
    state:
      present

- name: Yum install pip rpm
  yum:
    name:
      - python-pip
    state:
      present

- name:  Install docker-py package.
  pip:
    name: docker-py

- name: Pull pause image
  docker_image:
    name: registry.cn-hangzhou.aliyuncs.com/google_containers/pause-amd64:{{ PAUSE_VERSION }}

- name: Retag pause image
  shell: docker tag registry.cn-hangzhou.aliyuncs.com/google_containers/pause-amd64:{{ PAUSE_VERSION }} k8s.gcr.io/pause:{{ PAUSE_VERSION }}

- name: Pull flannel image
  docker_image:
    name: registry.cn-hangzhou.aliyuncs.com/kubernetes_containers/flannel:{{ FLANNEL_VERSION }}

- name: Retag flannel image
  shell: docker tag registry.cn-hangzhou.aliyuncs.com/kubernetes_containers/flannel:{{ FLANNEL_VERSION }} quay.io/coreos/flannel:{{ FLANNEL_VERSION }}

# kubeadm join --token bfas7b.nujnsjbap4ymf32v 192.168.93.136:6443 --discovery-token-ca-cert-hash sha256:2b3d0c381202dff735e02ba411dc5c7c0bbfa22339d86642d9cde1296656b3b2
