---
- hosts: k8smaster
  tasks:
#- name: echo hello world
#    shell: echo {{ hostvars['mynode11']['ansible_system_vendor'] }}
  - name: Check registry container
    shell: docker images | grep registry
    ignore_errors: True
    register: reg_output

  - name: Load registry image
    shell: docker load --input /storage/docker-image/library/registry_2.tar
    when: reg_output.stdout=="" or reg_output.stdout.split()[0] != "registry"

  - name: Create a data container
    docker_container:
      name: registry
      image: registry:2
      restart_policy: always
      volumes:
        - /storage/docker-registry/:/var/lib/registry
      ports:
        - "5000:5000"
