- name: Disable firewalld service
  service: name=firewalld state=stopped enabled=no

- name: yum install -y yum-utils device-mapper-persistent-data lvm2
  yum: 
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state:
      present
      
- name: Add repository
  shell: yum-config-manager add-repo https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo

- name: Disable docker edge & test repo
  shell: yum-config-manager --disable docker-ce-edge && yum-config-manager --disable docker-ce-test

- name: yum install -y docker
  yum: name=docker-ce-18.06.1.ce-3.el7 state=present

- name: Enable and start Docker service
  service: name=docker state=started enabled=yes

- name: Try Docker service
  shell: docker run hello-world

- name: Transfer kubernetes.repo
  copy: src=kubernetes.repo dest=/etc/yum.repos.d/kubernetes.repo

- name: yum install -y kubelet kubeadm kubectl
  yum: 
    name:
      - kubelet 
      - kubeadm 
      - kubectl
    state:
      present

- name: Transfer file k8s.conf
  copy: src=k8s.conf dest=/etc/sysctl.d/k8s.conf

- name: Set system parameters for k8s
  shell: sysctl --system

- name: Enable and start kubelet service
  service: name=kubelet state=started enabled=yes

- name: Pull kube-apiserver image 
  docker_image:
    name: registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver-amd64:{{ K8S_VERSION }}

- name: Retag kube-apiserver image
  shell: docker tag registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver-amd64:{{ K8S_VERSION }} k8s.gcr.io/kube-apiserver:{{ K8S_VERSION }}

- name: Pull kube-controller-manager image
  docker_image:
    name: registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager-amd64:{{ K8S_VERSION }}

- name: Retag kube-controller-manager image
  shell: docker tag registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager-amd64:{{ K8S_VERSION }} k8s.gcr.io/kube-controller-manager:{{ K8S_VERSION }}

- name: Pull kube-scheduler image
  docker_image:
    name: registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler-amd64:{{ K8S_VERSION }}

- name: Retag kube-scheduler image
  shell: docker tag registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler-amd64:{{ K8S_VERSION }} k8s.gcr.io/kube-scheduler:{{ K8S_VERSION }}

- name: Pull kube-proxy image
  docker_image:
    name: registry.cn-hangzhou.aliyuncs.com/google_containers/kube-proxy-amd64:{{ K8S_VERSION }}

- name: Retag kube-proxy image
  shell: docker tag registry.cn-hangzhou.aliyuncs.com/google_containers/kube-proxy-amd64:{{ K8S_VERSION }} k8s.gcr.io/kube-proxy:{{ K8S_VERSION }}

- name: Pull etcd image
  docker_image:
    name: registry.cn-hangzhou.aliyuncs.com/google_containers/etcd-amd64:{{ ETCD_VERSION }}

- name: Retag etcd image
  shell: docker tag registry.cn-hangzhou.aliyuncs.com/google_containers/etcd-amd64:{{ ETCD_VERSION }} k8s.gcr.io/etcd:{{ ETCD_VERSION }}

- name: Pull pause image
  docker_image:
    name: registry.cn-hangzhou.aliyuncs.com/google_containers/pause-amd64:{{ PAUSE_VERSION }}

- name: Retag pause image
  shell: docker tag registry.cn-hangzhou.aliyuncs.com/google_containers/pause-amd64:{{ PAUSE_VERSION }} k8s.gcr.io/pause:{{ PAUSE_VERSION }}

- name: Pull coredns image
  docker_image:
    name: registry.cn-hangzhou.aliyuncs.com/google_containers/coredns:{{ DNS_VERSION }}

- name: Retag coredns image
  shell: docker tag registry.cn-hangzhou.aliyuncs.com/google_containers/coredns:{{ DNS_VERSION }} k8s.gcr.io/coredns:{{ DNS_VERSION }}

- name: Pull flannel image
  docker_image:
    name: registry.cn-hangzhou.aliyuncs.com/kubernetes_containers/flannel:{{ FLANNEL_VERSION }}

- name: Retag flannel image
  shell: docker tag registry.cn-hangzhou.aliyuncs.com/kubernetes_containers/flannel:{{ FLANNEL_VERSION }} quay.io/coreos/flannel:{{ FLANNEL_VERSION }}

- name: Pull kubernetes-dashboard image
  docker_image:
    name: registry.cn-hangzhou.aliyuncs.com/google_containers/kubernetes-dashboard-amd64:{{ DASHBOARD_VERSION }}

- name: Retag kubernetes-dashboard image
  shell: docker tag registry.cn-hangzhou.aliyuncs.com/google_containers/kubernetes-dashboard-amd64:{{ DASHBOARD_VERSION }} k8s.gcr.io/kubernetes-dashboard:{{ DASHBOARD_VERSION }}

